/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.Session;
import config.dbConnector;
import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import user.changePass;


public class AccountDetails extends javax.swing.JFrame {
    private String currentImagePath = "";
    public void setAccountDetails(String name, String emailVal, String contact, 
                               String user, String type, String status, String imgPath) {
    fullname.setText(name);
    email.setText(emailVal);
    contactnumber.setText(contact);
    username.setText(user);
    usertype.setText(type);
    activestatus.setText(status);

    if (imgPath != null && !imgPath.isEmpty()) {
        ImageIcon icon = new ImageIcon(imgPath);
        Image scaled = icon.getImage().getScaledInstance(
            aimage.getWidth(), aimage.getHeight(), Image.SCALE_SMOOTH
        );
        aimage.setIcon(new ImageIcon(scaled));
    }
}

    

   
    public AccountDetails() {
    initComponents();
    setLocationRelativeTo(null); // ← add this line
}
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        page = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        contactnumber = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        usertype = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        activestatus = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel14 = new javax.swing.JPanel();
        aimage = new javax.swing.JLabel();
        TruckID = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        changepass = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        page.setBackground(new java.awt.Color(255, 255, 255));
        page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel7.setText("Full Name           :");
        page.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 90, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel9.setText("Email                  :");
        page.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 90, -1));

        fullname.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        fullname.setText(" ");
        page.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 140, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel11.setText("Contact Number      :");
        page.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 110, -1));

        contactnumber.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        contactnumber.setText(" ");
        page.add(contactnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 140, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel13.setText("User Type            :");
        page.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 90, -1));

        usertype.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        usertype.setText(" ");
        page.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 140, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel15.setText("Active Status      :");
        page.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 90, -1));

        activestatus.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        activestatus.setText(" ");
        page.add(activestatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 140, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel8.setText("Username           :");
        page.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 90, -1));

        jLabel10.setBackground(new java.awt.Color(255, 102, 102));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/123.jpg"))); // NOI18N
        page.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 30));

        jLabel12.setBackground(new java.awt.Color(255, 102, 102));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/123.jpg"))); // NOI18N
        page.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 60, 30));
        page.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 280, 10));
        page.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 560, 12));
        page.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 570, 20));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Account Details");
        page.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 440, 25));
        page.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 560, 12));

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(aimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 230));

        TruckID.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        TruckID.setText(" ");
        jPanel14.add(TruckID, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 70, 140, -1));

        page.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 250));

        username.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        username.setText(" ");
        page.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 140, -1));

        email.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        email.setText(" ");
        page.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 140, -1));

        update.setBackground(new java.awt.Color(0, 51, 204));
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        page.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 100, 40));

        changepass.setBackground(new java.awt.Color(204, 204, 204));
        changepass.setForeground(new java.awt.Color(51, 51, 51));
        changepass.setText("Change Pass");
        changepass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changepassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changepassMouseExited(evt);
            }
        });
        changepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepassActionPerformed(evt);
            }
        });
        page.add(changepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 100, 40));

        cancel.setBackground(new java.awt.Color(255, 0, 0));
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Back");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        page.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 100, 40));

        getContentPane().add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        adminDashboard ads=new adminDashboard();
        ads.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseExited

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseEntered

    private void changepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepassActionPerformed
       ChangPass cp = new ChangPass();
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_changepassActionPerformed

    private void changepassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepassMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_changepassMouseExited

    private void changepassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepassMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_changepassMouseEntered

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMouseExited

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
try {
        Session session = Session.getInstance();
        dbConnector dbc = new dbConnector();
        String sql = "SELECT * FROM tbl_user WHERE u_id = ?";
        PreparedStatement pst = dbc.getConnection().prepareStatement(sql);
        pst.setInt(1, session.getUid());
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            AccountUpdate au = new AccountUpdate();
            au.setAccountData(
                rs.getString("u_name"),
                rs.getString("u_email"),
                rs.getString("u_number"),
                rs.getString("u_username"),
                rs.getString("u_type"),
                rs.getString("u_status"),
                rs.getString("u_image")
            );
            au.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "User not found!");
        }

        rs.close();
        pst.close();
        dbc.close();

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Database error: " + ex.getMessage());
    }

    
    }//GEN-LAST:event_updateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel TruckID;
    public javax.swing.JLabel activestatus;
    public javax.swing.JLabel aimage;
    public javax.swing.JButton cancel;
    public javax.swing.JButton changepass;
    public javax.swing.JLabel contactnumber;
    public javax.swing.JLabel email;
    public javax.swing.JLabel fullname;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel page;
    public javax.swing.JButton update;
    public javax.swing.JLabel username;
    public javax.swing.JLabel usertype;
    // End of variables declaration//GEN-END:variables
}
