/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import static admin.CreateUserForm.getHeightFromWidth;
import config.PanelPrinter;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author mypc
 */
public class IndividualPrinting extends javax.swing.JFrame {

    /**
     * Creates new form IndividualPrinting
     */
    public IndividualPrinting() {
        initComponents();
    }
    
    public  ImageIcon ResizeImage(String ImagePath, byte[] pic, JLabel label) {
    ImageIcon MyImage = null;
        if(ImagePath !=null){
            MyImage = new ImageIcon(ImagePath);
        }else{
            MyImage = new ImageIcon(pic);
        }
        
    int newHeight = getHeightFromWidth(ImagePath, label.getWidth());

    Image img = MyImage.getImage();
    Image newImg = img.getScaledInstance(label.getWidth(), newHeight, Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
}
    
     Color shok = new Color(160,3,0);
     Color redd = new Color(198,20,17);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BackPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        page = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        completename1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cnum = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        utype = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ustatus = new javax.swing.JLabel();
        un = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 29, 29));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackPanel.setBackground(new java.awt.Color(160, 3, 0));
        BackPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackPanelMouseExited(evt);
            }
        });
        BackPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BACK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        BackPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 10));

        jPanel2.add(BackPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 50, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PRINTING FORMS");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 30));

        page.setBackground(new java.awt.Color(255, 255, 255));
        page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SHOOK TRUCKING CORP.");
        page.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 18, 410, 25));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bulacao, Talisay City, Cebu");
        page.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 390, 18));

        UserID.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        UserID.setText(" ");
        page.add(UserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 140, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel5.setText("User ID                 :");
        page.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel7.setText("Complete Name   :");
        page.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 90, -1));

        completename1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        completename1.setText(" ");
        page.add(completename1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 140, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel9.setText("Email                   :");
        page.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 90, -1));

        email.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        email.setText(" ");
        page.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 140, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel11.setText("Cell Number        :");
        page.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, -1));

        cnum.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cnum.setText(" ");
        page.add(cnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 140, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel13.setText("User Type            :");
        page.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 90, -1));

        utype.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        utype.setText(" ");
        page.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 140, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel15.setText("Status                 :");
        page.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 90, -1));

        ustatus.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        ustatus.setText(" ");
        page.add(ustatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 140, -1));

        un.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        un.setText(" ");
        page.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 140, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel8.setText("User Name          :");
        page.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, -1));

        jLabel10.setBackground(new java.awt.Color(255, 102, 102));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/123.jpg"))); // NOI18N
        page.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 30));

        jLabel12.setBackground(new java.awt.Color(255, 102, 102));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/123.jpg"))); // NOI18N
        page.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 60, 30));
        page.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 340, 12));

        jPanel1.add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 410, 570));

        pPrint.setBackground(new java.awt.Color(160, 3, 0));
        pPrint.setForeground(new java.awt.Color(204, 204, 204));
        pPrint.setText("PRINT");
        pPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pPrintMouseClicked(evt);
            }
        });
        pPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPrintActionPerformed(evt);
            }
        });
        jPanel1.add(pPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        adminDashboard ads=new adminDashboard();
        ads.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void BackPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackPanelMouseClicked
        usersForm uf=new usersForm();
        uf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackPanelMouseClicked

    private void BackPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackPanelMouseEntered
        BackPanel.setBackground(redd);
    }//GEN-LAST:event_BackPanelMouseEntered

    private void BackPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackPanelMouseExited
        BackPanel.setBackground(shok);
    }//GEN-LAST:event_BackPanelMouseExited

    private void pPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPrintActionPerformed
       JPanel myPanel = new JPanel();
       PanelPrinter pPrint = new PanelPrinter(page);
       pPrint.printPanel();
    }//GEN-LAST:event_pPrintActionPerformed

    private void pPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPrintMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pPrintMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndividualPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndividualPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndividualPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndividualPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndividualPrinting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackPanel;
    public javax.swing.JLabel UserID;
    public javax.swing.JLabel cnum;
    public javax.swing.JLabel completename1;
    public javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton pPrint;
    private javax.swing.JPanel page;
    public javax.swing.JLabel un;
    public javax.swing.JLabel ustatus;
    public javax.swing.JLabel utype;
    // End of variables declaration//GEN-END:variables
}
