/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.Session;
import config.dbConnector;
import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.red;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;


public class TrucksForm extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboard
     */
    public TrucksForm() {
        initComponents();
        displayData();
 
    }
    
    boolean checkadd = true;
    
    Color shok = new Color(160,3,0);
    Color redd = new Color(198,20,17);
    
    
    
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs;
            rs = dbc.getData("SELECT truck_id, plate_number, model, capacity, truck_status FROM tbl_truck");
            truckTable.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());
        
        }
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Clear = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        p_add2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        p_add1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        p_add = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Prntbuttn1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        Prntbuttn = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        UserID = new javax.swing.JLabel();
        p_edit = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        truckTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        tID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PlateNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Model = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Capacity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTruckStatus = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 29, 29));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackPanel.setBackground(new java.awt.Color(160, 3, 0));
        BackPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackPanelMouseExited(evt);
            }
        });
        BackPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BACK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        BackPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 10));

        jPanel1.add(BackPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 50, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TRUCK FORM");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Clear.setBackground(new java.awt.Color(160, 3, 0));
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClearMouseExited(evt);
            }
        });
        Clear.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("CLEAR");
        Clear.add(jLabel17);
        jLabel17.setBounds(0, 10, 70, 10);

        jPanel2.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 70, 30));

        p_add2.setBackground(new java.awt.Color(160, 3, 0));
        p_add2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_add2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_add2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_add2MouseExited(evt);
            }
        });
        p_add2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("REMOVE");
        p_add2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 10));

        jPanel2.add(p_add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 80, 30));

        p_add1.setBackground(new java.awt.Color(160, 3, 0));
        p_add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_add1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_add1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_add1MouseExited(evt);
            }
        });
        p_add1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("SELECT");
        p_add1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 10));

        jPanel2.add(p_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 80, 30));

        jPanel5.setBackground(new java.awt.Color(204, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setText("jTextField2");
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 140));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 160));

        p_add.setBackground(new java.awt.Color(160, 3, 0));
        p_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_addMouseExited(evt);
            }
        });
        p_add.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADD");
        p_add.add(jLabel4);
        jLabel4.setBounds(0, 10, 70, 10);

        jPanel2.add(p_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 70, 30));

        Prntbuttn1.setBackground(new java.awt.Color(160, 3, 0));
        Prntbuttn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Prntbuttn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Prntbuttn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Prntbuttn1MouseExited(evt);
            }
        });
        Prntbuttn1.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("DELETE");
        Prntbuttn1.add(jLabel21);
        jLabel21.setBounds(0, 10, 70, 10);

        jPanel2.add(Prntbuttn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 70, 30));

        Prntbuttn.setBackground(new java.awt.Color(160, 3, 0));
        Prntbuttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrntbuttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PrntbuttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PrntbuttnMouseExited(evt);
            }
        });
        Prntbuttn.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("PRINT");
        Prntbuttn.add(jLabel22);
        jLabel22.setBounds(0, 10, 70, 10);

        jPanel2.add(Prntbuttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 70, 30));

        UserID.setBackground(new java.awt.Color(0, 0, 0));
        UserID.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        UserID.setForeground(new java.awt.Color(153, 153, 153));
        UserID.setText("ID");
        jPanel2.add(UserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 30, -1));

        p_edit.setBackground(new java.awt.Color(160, 3, 0));
        p_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_editMouseExited(evt);
            }
        });
        p_edit.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("UPDATE");
        p_edit.add(jLabel20);
        jLabel20.setBounds(0, 10, 70, 10);

        jPanel2.add(p_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 70, 30));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Current User :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 70, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("TRUCK");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 50, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login-background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 200, 450));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 440));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        truckTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        truckTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                truckTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(truckTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 430, 440));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Truck ID");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 50, 10));

        tID.setBackground(new java.awt.Color(215, 215, 215));
        tID.setEnabled(false);
        jPanel3.add(tID, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 50, 20));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Plate Number");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 80, 10));

        PlateNumber.setBackground(new java.awt.Color(215, 215, 215));
        jPanel3.add(PlateNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 140, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Model");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 90, 10));

        Model.setBackground(new java.awt.Color(215, 215, 215));
        jPanel3.add(Model, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 140, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Capacity");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, 10));

        Capacity.setBackground(new java.awt.Color(215, 215, 215));
        jPanel3.add(Capacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 140, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Truck Status");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, -1, 10));

        jTruckStatus.setBackground(new java.awt.Color(255, 51, 51));
        jTruckStatus.setForeground(new java.awt.Color(255, 255, 255));
        jTruckStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AVAILABLE", "NOT AVAILABLE" }));
        jTruckStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTruckStatusActionPerformed(evt);
            }
        });
        jPanel3.add(jTruckStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 140, 30));

        jLabel14.setBackground(new java.awt.Color(255, 102, 102));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/123.jpg"))); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 60, 40));

        jLabel15.setBackground(new java.awt.Color(115, 5, 5));
        jLabel15.setFont(new java.awt.Font("Stencil", 3, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(128, 0, 0));
        jLabel15.setText("SHOOK TRUCKING");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         adminDashboard ads=new adminDashboard();
            ads.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getInstance();
        UserID.setText(""+sess.getUid());
        
    }//GEN-LAST:event_formWindowActivated

    private void p_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseEntered
        p_add.setBackground(redd);   
    }//GEN-LAST:event_p_addMouseEntered

    private void p_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseExited
     
        p_add.setBackground(shok);
    }//GEN-LAST:event_p_addMouseExited

    private void BackPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackPanelMouseEntered
        BackPanel.setBackground(redd);
    }//GEN-LAST:event_BackPanelMouseEntered

    private void BackPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackPanelMouseExited
        BackPanel.setBackground(shok);
    }//GEN-LAST:event_BackPanelMouseExited

    private void p_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseClicked
        if(checkadd){
            
            if(PlateNumber.getText().isEmpty()||Model.getText().isEmpty()||Capacity.getText().isEmpty()){
               JOptionPane.showMessageDialog(null, "All Field are Required!");      
            }else{
                dbConnector dbc = new dbConnector();
                dbc.insertData("INSERT INTO tbl_truck(plate_number, model, capacity, truck_status, truck_image)VALUES('"+PlateNumber.getText()+"','"+Model.getText()+"','"+Capacity.getText()+"','"+jTruckStatus.getSelectedItem()+"','')");
                JOptionPane.showMessageDialog(null, "Successfully Added");   
                displayData();
                tID.setText("");
                PlateNumber.setText("");
                Model.setText("");
                Capacity.setText("");
                jTruckStatus.setSelectedItem(""); 
                      
            }
        }
    }//GEN-LAST:event_p_addMouseClicked

    private void BackPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackPanelMouseClicked
        adminDashboard ads=new adminDashboard();
        ads.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackPanelMouseClicked

    private void jTruckStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTruckStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTruckStatusActionPerformed

    private void p_add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p_add1MouseClicked

    private void p_add1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p_add1MouseEntered

    private void p_add1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p_add1MouseExited

    private void p_add2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_p_add2MouseClicked

    private void p_add2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p_add2MouseEntered

    private void p_add2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p_add2MouseExited

    private void truckTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_truckTableMouseClicked
     int rowIndex = truckTable.getSelectedRow();
        
        if(rowIndex<0){
            JOptionPane.showMessageDialog(null, "Please select Item!");
        }else{
          
            
            try{
            dbConnector dbc = new dbConnector();
            TableModel tbl = truckTable.getModel();
            ResultSet rs = dbc.getData("SELECT*FROM tbl_truck WHERE truck_id = '"+tbl.getValueAt(rowIndex, 0)+"'");
            if(rs.next()){
     
                tID.setText(""+rs.getInt("truck_id"));
                PlateNumber.setText(""+rs.getString("plate_number"));
                Model.setText(""+rs.getString("model"));
                Capacity.setText(""+rs.getString("capacity"));
                jTruckStatus.setSelectedItem(""+rs.getString("truck_status"));              
                p_add.setEnabled(false);
                jLabel4.setForeground(red);
                checkadd = false;
               
    
           
            }
            }catch(SQLException ex){  
              System.out.println(""+ex);
            }
        
        }
    
    }//GEN-LAST:event_truckTableMouseClicked

    private void ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseClicked
     checkadd = true;
     jLabel4.setForeground(black);
     tID.setText("");
                PlateNumber.setText("");
                Model.setText("");
                Capacity.setText("");
                jTruckStatus.setSelectedItem(""); 
    }//GEN-LAST:event_ClearMouseClicked

    private void ClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseEntered
     Clear.setBackground(redd);  
    }//GEN-LAST:event_ClearMouseEntered

    private void ClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseExited
      Clear.setBackground(shok);
    }//GEN-LAST:event_ClearMouseExited

    private void PrntbuttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrntbuttnMouseExited
        Prntbuttn.setBackground(shok);
    }//GEN-LAST:event_PrntbuttnMouseExited

    private void PrntbuttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrntbuttnMouseEntered
        Prntbuttn.setBackground(redd);
    }//GEN-LAST:event_PrntbuttnMouseEntered

    private void PrntbuttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrntbuttnMouseClicked

    }//GEN-LAST:event_PrntbuttnMouseClicked

    private void Prntbuttn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Prntbuttn1MouseExited
        Prntbuttn1.setBackground(shok);
    }//GEN-LAST:event_Prntbuttn1MouseExited

    private void Prntbuttn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Prntbuttn1MouseEntered
        Prntbuttn1.setBackground(redd);
    }//GEN-LAST:event_Prntbuttn1MouseEntered

    private void Prntbuttn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Prntbuttn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Prntbuttn1MouseClicked

    private void p_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_editMouseExited
        p_edit.setBackground(shok);
    }//GEN-LAST:event_p_editMouseExited

    private void p_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_editMouseEntered
        p_edit.setBackground(redd);
    }//GEN-LAST:event_p_editMouseEntered

    private void p_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_editMouseClicked
        if(tID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Select Trucks First! ");
        }else{
            if(PlateNumber.getText().isEmpty()||Model.getText().isEmpty()||Capacity.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "All Field are Required!");
            }else{
                dbConnector dbc = new dbConnector();
                dbc.updateData("UPDATE tbl_truck SET plate_number = '"+PlateNumber.getText()+"',"
                    + "model ='"+Model.getText()+"',"
                    + "capacity = '"+Capacity.getText()+"', "
                    + "truck_status = '"+jTruckStatus.getSelectedItem()+"' WHERE truck_id  = '"+tID.getText()+"'");
                JOptionPane.showMessageDialog(null, "Updated Successfully! ");
                displayData();
                tID.setText("");
                PlateNumber.setText("");
                Model.setText("");
                Capacity.setText("");
                jTruckStatus.setSelectedItem("");

            }

        }

    }//GEN-LAST:event_p_editMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrucksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrucksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrucksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrucksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrucksForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackPanel;
    public javax.swing.JTextField Capacity;
    private javax.swing.JPanel Clear;
    public javax.swing.JTextField Model;
    public javax.swing.JTextField PlateNumber;
    private javax.swing.JPanel Prntbuttn;
    private javax.swing.JPanel Prntbuttn1;
    private javax.swing.JLabel UserID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JComboBox<String> jTruckStatus;
    private javax.swing.JPanel p_add;
    private javax.swing.JPanel p_add1;
    private javax.swing.JPanel p_add2;
    private javax.swing.JPanel p_edit;
    public javax.swing.JTextField tID;
    private javax.swing.JTable truckTable;
    // End of variables declaration//GEN-END:variables
}
